package cn.studypilot.assessment.service;
import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper;
import cn.studypilot.assessment.model.*; import cn.studypilot.assessment.repository.AssessmentRepository; import cn.studypilot.common.exception.*; import cn.studypilot.model.dto.*; import cn.studypilot.model.gateway.ModelGateway;
import java.time.Duration; import java.util.*; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @ConditionalOnProperty(prefix="studypilot.database",name="url")
public class AssessmentService {
 private final AssessmentRepository repo; private final ModelGateway model; private final ObjectMapper json;
 public AssessmentService(AssessmentRepository repo,ModelGateway model,ObjectMapper json){this.repo=repo;this.model=model;this.json=json;}
 public long start(long project,long exam){return repo.createAttempt(project,exam);}
 @Transactional public AssessmentReport submit(long project,long attempt,List<SubmittedAnswer> submissions){
  AttemptContext context=repo.findInProgressAttempt(project,attempt); Map<Long,String> input=new HashMap<>(); for(var s:submissions){if(s.answer()==null||s.answer().isBlank()||input.put(s.itemId(),s.answer().trim())!=null)throw new IllegalArgumentException("每道题必须且只能提交一次非空答案");}
  if(input.size()!=context.items().size()||!context.items().stream().allMatch(i->input.containsKey(i.id())))throw new IllegalArgumentException("提交答案必须覆盖本次试卷全部题目");
  List<GradedAnswer> graded=new ArrayList<>();for(var item:context.items()){var result=grade(item,input.get(item.id())); graded.add(result);repo.saveGradedAnswer(attempt,result,input.get(item.id()));double mastery=result.score()/result.maxScore();repo.updateMastery(project,result.knowledgePoint(),mastery);if(mastery<.6){repo.recordWrongAnswer(project,attempt,result);repo.recordRecommendation(project,attempt,result.knowledgePoint(),"建议复习“"+result.knowledgePoint()+"”的核心概念后再完成一组练习。");}}
  double total=graded.stream().mapToDouble(GradedAnswer::score).sum();double max=graded.stream().mapToDouble(GradedAnswer::maxScore).sum();repo.completeAttempt(attempt,total);return new AssessmentReport(attempt,total,max,List.copyOf(graded)); }
 private GradedAnswer grade(AssessableItem item,String answer){if("SINGLE_CHOICE".equals(item.type())){boolean ok=item.answer().trim().equalsIgnoreCase(answer.trim());return new GradedAnswer(item.id(),item.knowledgePoint(),ok?item.maxScore():0,item.maxScore(),ok?"答案正确。":"答案不正确，请结合解析复习。","RULE_GRADED");}try{String prompt="依据参考答案评价学生简答。仅返回 JSON：{score:0到"+item.maxScore()+",feedback:简短中文反馈}。参考答案："+item.answer()+"\n学生答案："+answer;JsonNode value=json.readTree(model.complete(new ModelRequest(ModelTaskType.SHORT_ANSWER_ASSESSMENT,List.of(new ModelMessage("system","你是严谨的课程评分助手。"),new ModelMessage("user",prompt)),0,300,Duration.ofSeconds(60))).content());double score=value.path("score").asDouble(-1);String feedback=value.path("feedback").asText("").trim();if(score<0||score>item.maxScore()||feedback.isBlank())throw new BusinessException(ErrorCode.MODEL_OUTPUT_INVALID,"简答题评分结果格式不合法");return new GradedAnswer(item.id(),item.knowledgePoint(),score,item.maxScore(),feedback,"MODEL_GRADED");}catch(BusinessException e){throw e;}catch(Exception e){throw new BusinessException(ErrorCode.MODEL_OUTPUT_INVALID,"简答题评分结果无法解析");}}
}
