SET search_path TO studypilot, public;

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS model_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  task_type TEXT NOT NULL,
  model_name TEXT NOT NULL,
  generation_options JSONB NOT NULL DEFAULT '{}'::jsonb,
  elapsed_ms BIGINT NOT NULL CHECK (elapsed_ms >= 0),
  succeeded BOOLEAN NOT NULL,
  end_reason TEXT NOT NULL,
  result_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_id TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
