SET search_path TO studypilot, public;

CREATE TABLE IF NOT EXISTS qa_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS qa_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES qa_sessions(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('USER', 'ASSISTANT')),
  content TEXT NOT NULL,
  model_run_id BIGINT REFERENCES model_runs(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS qa_retrieval_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assistant_message_id BIGINT NOT NULL REFERENCES qa_messages(id) ON DELETE CASCADE,
  document_id BIGINT REFERENCES documents(id) ON DELETE SET NULL,
  page_number INTEGER NOT NULL CHECK (page_number > 0),
  chunk_id BIGINT REFERENCES document_chunks(id) ON DELETE SET NULL,
  rank_position INTEGER NOT NULL CHECK (rank_position > 0),
  score NUMERIC(8, 6) NOT NULL,
  excerpt_snapshot TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (assistant_message_id, rank_position)
);

CREATE TABLE IF NOT EXISTS qa_citations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assistant_message_id BIGINT NOT NULL REFERENCES qa_messages(id) ON DELETE CASCADE,
  retrieval_record_id BIGINT REFERENCES qa_retrieval_records(id) ON DELETE SET NULL,
  document_id BIGINT REFERENCES documents(id) ON DELETE SET NULL,
  document_name_snapshot TEXT NOT NULL,
  page_number INTEGER NOT NULL CHECK (page_number > 0),
  excerpt_snapshot TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
