SET search_path TO studypilot, public;

CREATE TABLE IF NOT EXISTS source_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  document_id BIGINT REFERENCES documents(id) ON DELETE SET NULL,
  source_page_number INTEGER CHECK (source_page_number > 0),
  question_type TEXT NOT NULL CHECK (question_type IN ('SINGLE_CHOICE', 'SHORT_ANSWER')),
  stem TEXT NOT NULL,
  reference_answer TEXT NOT NULL,
  analysis TEXT NOT NULL DEFAULT '',
  raw_source_snapshot TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS question_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES source_questions(id) ON DELETE CASCADE,
  option_key TEXT NOT NULL CHECK (option_key IN ('A', 'B', 'C', 'D', 'E', 'F')),
  option_text TEXT NOT NULL,
  is_correct BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (question_id, option_key)
);

CREATE TABLE IF NOT EXISTS question_knowledge_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES source_questions(id) ON DELETE CASCADE,
  knowledge_point TEXT NOT NULL,
  confidence NUMERIC(5, 4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (question_id, knowledge_point)
);

CREATE TABLE IF NOT EXISTS exam_blueprints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  specification JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mock_exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  blueprint_id BIGINT REFERENCES exam_blueprints(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  generation_run_id BIGINT REFERENCES model_runs(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mock_exam_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id BIGINT NOT NULL REFERENCES mock_exams(id) ON DELETE CASCADE,
  source_question_id BIGINT REFERENCES source_questions(id) ON DELETE SET NULL,
  ordinal INTEGER NOT NULL CHECK (ordinal > 0),
  question_type TEXT NOT NULL CHECK (question_type IN ('SINGLE_CHOICE', 'SHORT_ANSWER')),
  prompt TEXT NOT NULL,
  options JSONB NOT NULL DEFAULT '[]'::jsonb,
  answer TEXT NOT NULL,
  analysis TEXT NOT NULL DEFAULT '',
  knowledge_point TEXT NOT NULL,
  score NUMERIC(6, 2) NOT NULL CHECK (score > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (exam_id, ordinal)
);

CREATE TABLE IF NOT EXISTS question_validation_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_item_id BIGINT NOT NULL REFERENCES mock_exam_items(id) ON DELETE CASCADE,
  validation_type TEXT NOT NULL,
  passed BOOLEAN NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
