SET search_path TO studypilot, public;

CREATE TABLE IF NOT EXISTS exam_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id BIGINT NOT NULL REFERENCES mock_exams(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('IN_PROGRESS', 'SUBMITTED', 'GRADED')),
  submitted_at TIMESTAMPTZ,
  total_score NUMERIC(8, 2),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attempt_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id BIGINT NOT NULL REFERENCES exam_attempts(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES mock_exam_items(id) ON DELETE RESTRICT,
  answer TEXT NOT NULL,
  score NUMERIC(8, 2),
  feedback TEXT NOT NULL DEFAULT '',
  grading_status TEXT NOT NULL CHECK (grading_status IN ('PENDING', 'RULE_GRADED', 'MODEL_GRADED', 'FAILED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (attempt_id, item_id)
);

CREATE TABLE IF NOT EXISTS grading_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_answer_id BIGINT NOT NULL REFERENCES attempt_answers(id) ON DELETE CASCADE,
  model_run_id BIGINT REFERENCES model_runs(id) ON DELETE SET NULL,
  rubric_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  rationale TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wrong_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_answer_id BIGINT NOT NULL UNIQUE REFERENCES attempt_answers(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  knowledge_point TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mastery_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  knowledge_point TEXT NOT NULL,
  mastery NUMERIC(5, 4) NOT NULL CHECK (mastery BETWEEN 0 AND 1),
  evidence_count INTEGER NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (project_id, knowledge_point)
);

CREATE TABLE IF NOT EXISTS recommendation_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  knowledge_point TEXT NOT NULL,
  recommendation TEXT NOT NULL,
  source_attempt_id BIGINT REFERENCES exam_attempts(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS study_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  recommendation_id BIGINT REFERENCES recommendation_records(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('PENDING', 'DONE', 'CANCELLED')),
  due_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
