package cn.studypilot.assessment.repository;
import cn.studypilot.assessment.model.*;
import cn.studypilot.common.exception.ResourceNotFoundException;
import java.util.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.namedparam.*;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Repository;
@Repository @ConditionalOnProperty(prefix="studypilot.database",name="url")
public class JdbcAssessmentRepository implements AssessmentRepository {
 private final NamedParameterJdbcTemplate jdbc; public JdbcAssessmentRepository(NamedParameterJdbcTemplate jdbc){this.jdbc=jdbc;}
 public long createAttempt(long projectId,long examId){var key=new GeneratedKeyHolder();int n=jdbc.update("INSERT INTO studypilot.exam_attempts (exam_id,status) SELECT id,'IN_PROGRESS' FROM studypilot.mock_exams WHERE id=:examId AND project_id=:projectId",new MapSqlParameterSource().addValue("examId",examId).addValue("projectId",projectId),key,new String[]{"id"});if(n!=1||key.getKey()==null)throw new ResourceNotFoundException("模拟卷不存在或不属于当前项目");return key.getKey().longValue();}
 public AttemptContext findInProgressAttempt(long projectId,long attemptId){var rows=jdbc.query("SELECT a.exam_id,i.id,i.question_type,i.answer,i.knowledge_point,i.score FROM studypilot.exam_attempts a JOIN studypilot.mock_exams e ON e.id=a.exam_id JOIN studypilot.mock_exam_items i ON i.exam_id=e.id WHERE a.id=:attemptId AND e.project_id=:projectId AND a.status='IN_PROGRESS' ORDER BY i.ordinal",Map.of("attemptId",attemptId,"projectId",projectId),(r,n)->new AssessableItem(r.getLong("id"),r.getString("question_type"),r.getString("answer"),r.getString("knowledge_point"),r.getDouble("score")));if(rows.isEmpty())throw new ResourceNotFoundException("作答记录不存在、不属于当前项目或已提交");long exam=jdbc.queryForObject("SELECT exam_id FROM studypilot.exam_attempts WHERE id=:id",Map.of("id",attemptId),Long.class);return new AttemptContext(attemptId,exam,rows);}
 public void saveGradedAnswer(long attempt,GradedAnswer graded,String answer){var key=new GeneratedKeyHolder();jdbc.update("INSERT INTO studypilot.attempt_answers (attempt_id,item_id,answer,score,feedback,grading_status) VALUES (:attempt,:item,:answer,:score,:feedback,:status)",new MapSqlParameterSource().addValue("attempt",attempt).addValue("item",graded.itemId()).addValue("answer",answer).addValue("score",graded.score()).addValue("feedback",graded.feedback()).addValue("status",graded.gradingStatus()),key,new String[]{"id"});jdbc.update("INSERT INTO studypilot.grading_details (attempt_answer_id,rubric_snapshot,rationale) VALUES (:id,CAST(:rubric AS jsonb),:rationale)",Map.of("id",key.getKey().longValue(),"rubric","{\"maxScore\":"+graded.maxScore()+"}","rationale",graded.feedback()));}
 public void completeAttempt(long attempt,double total){jdbc.update("UPDATE studypilot.exam_attempts SET status='GRADED',submitted_at=now(),total_score=:score,updated_at=now() WHERE id=:id",Map.of("id",attempt,"score",total));}
 public void updateMastery(long project,String point,double mastery){jdbc.update("INSERT INTO studypilot.mastery_records (project_id,knowledge_point,mastery,evidence_count) VALUES (:p,:k,:m,1) ON CONFLICT (project_id,knowledge_point) DO UPDATE SET mastery=(studypilot.mastery_records.mastery*studypilot.mastery_records.evidence_count+EXCLUDED.mastery)/(studypilot.mastery_records.evidence_count+1),evidence_count=studypilot.mastery_records.evidence_count+1,updated_at=now()",Map.of("p",project,"k",point,"m",mastery));}
 public void recordWrongAnswer(long project,long attempt,GradedAnswer graded){Long id=jdbc.queryForObject("SELECT id FROM studypilot.attempt_answers WHERE attempt_id=:a AND item_id=:i",Map.of("a",attempt,"i",graded.itemId()),Long.class);jdbc.update("INSERT INTO studypilot.wrong_questions (attempt_answer_id,project_id,knowledge_point) VALUES (:id,:p,:k)",Map.of("id",id,"p",project,"k",graded.knowledgePoint()));}
 public void recordRecommendation(long project,long attempt,String point,String text){jdbc.update("INSERT INTO studypilot.recommendation_records (project_id,knowledge_point,recommendation,source_attempt_id) VALUES (:p,:k,:t,:a)",Map.of("p",project,"a",attempt,"k",point,"t",text));}
}
