CREATE TABLE IF NOT EXISTS documents (
 id VARCHAR(36) PRIMARY KEY, name VARCHAR(240) NOT NULL, sha256 CHAR(64) NOT NULL UNIQUE,
 pages INT NOT NULL CHECK (pages>0), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
 id VARCHAR(36) PRIMARY KEY, title VARCHAR(120) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS messages (
 id VARCHAR(36) PRIMARY KEY, session_id VARCHAR(36) NOT NULL, role VARCHAR(12) NOT NULL,
 content MEDIUMTEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE,
 INDEX idx_messages_session(session_id,created_at),
 CHECK (role IN ('user','assistant')), CHECK(status IN ('complete','cancelled','failed'))
);
CREATE TABLE IF NOT EXISTS citations (
 id VARCHAR(36) PRIMARY KEY, message_id VARCHAR(36) NOT NULL, document_id VARCHAR(36),
 source_name VARCHAR(240) NOT NULL, page_number INT NOT NULL, excerpt TEXT NOT NULL,
 FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE,
 FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE SET NULL,
 CHECK(page_number>0)
);
CREATE TABLE IF NOT EXISTS plans (
 id VARCHAR(36) PRIMARY KEY, goal VARCHAR(400) NOT NULL, weak_points VARCHAR(600) NOT NULL,
 start_date DATE NOT NULL, days INT NOT NULL CHECK(days BETWEEN 1 AND 30),
 daily_minutes INT NOT NULL CHECK(daily_minutes BETWEEN 10 AND 480),
 version INT NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tasks (
 id VARCHAR(36) PRIMARY KEY, plan_id VARCHAR(36) NOT NULL, task_date DATE NOT NULL,
 title VARCHAR(240) NOT NULL, detail TEXT NOT NULL, minutes INT NOT NULL CHECK(minutes BETWEEN 5 AND 480),
 done BOOLEAN NOT NULL DEFAULT FALSE, completed_at TIMESTAMP NULL,
 FOREIGN KEY(plan_id) REFERENCES plans(id) ON DELETE CASCADE,
 INDEX idx_tasks_plan_date(plan_id,task_date)
);
CREATE TABLE IF NOT EXISTS plan_revisions (
 id VARCHAR(36) PRIMARY KEY, plan_id VARCHAR(36) NOT NULL, version INT NOT NULL,
 instruction VARCHAR(600) NOT NULL, snapshot MEDIUMTEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(plan_id) REFERENCES plans(id) ON DELETE CASCADE, UNIQUE(plan_id,version)
);
CREATE TABLE IF NOT EXISTS agent_events (
 id VARCHAR(36) PRIMARY KEY, run_id VARCHAR(36) NOT NULL, tool_name VARCHAR(80) NOT NULL,
 detail TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
